describe("the game logic can", () => {
	test.todo("move a villian");
	test.todo("gain power");
	test.todo("draw a villian card");
    test.todo("play an item card");
    test.todo("play an ally card");
    test.todo("play an effect card");
    test.todo("play a specialty card");
    test.todo("play a multiverse card");
    test.todo("play a variant card");
    test.todo("draw a fate card");
    test.todo("play a fate card");
	test.todo("discard cards");
	test.todo("perform a vanquish action");
	test.todo("relocate a card");
	test.todo("defeat a card");
	test.todo("remove a card");
	test.todo("activate an ability");
	test.todo("end a player's turn");
});